version: '3'
services:
  my-service:
    image: my-image
    ports:
      - "8080:80"
    environment:
      - environment=production

  frontend-service:
    image: frontend-image
    ports:
      - "8000:80"  
    environment:
      - WS_BACK_URL=http://my-service:80